mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # The View related to the Home page
    
    url(r'^$', 'mysite.views.home', name='home'),
    
    # Views related to the URLs in the Polls app
    # namespace is required when using names in the polls app to direct the urls
    # example: if trying to direct to /polls/ instead of setting an href
    #          to "/polls/" or "{% url 'index' %}", you must use "{% url 'polls:index' %}"  
    
    url(r'^polls/', include('polls.urls', namespace='polls')),
    
    # Views related to the Admin interface
    
    (r'^grappelli/', include('grappelli.urls')), 
    url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'polls.views.index', name='index'),
    url(r'^(?P<poll_id>\d+)$', 'polls.views.details', name='details'),
    url(r'^(?P<poll_id>\d+)/results/$', 'polls.views.results', name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote', name='vote'),
)

polls/models.py
from django.db import models
from django.utils import timezone

import datetime


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):
        return self.question
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <  now
    
    # override the default display of was_published_recently in the admin view
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published Recently?'
    
class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.choice_text
        

    
    

mysite/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def home(request):
    context = RequestContext(request)
    context_dict = {}
    return render_to_response('home.html', context_dict, context)

polls/views.py
from django.shortcuts import render_to_response, get_object_or_404, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse

from .models import Poll, Choice

def index(request):
    context = RequestContext(request)
    context_dict = {}
    
    # Get the top 5 most recent poll objects
    latest_polls_list = Poll.objects.order_by('-pub_date')[:5]
    context_dict['latest_polls_list'] = latest_polls_list
    return render_to_response('polls/index.html', context_dict, context)

def details(request, poll_id):
    context = RequestContext(request)
    context_dict = {}
    
    poll = get_object_or_404(Poll, pk=poll_id)
    context_dict['poll'] = poll
    
    return render_to_response('polls/details.html', context_dict, context)

def results(request, poll_id):
    context = RequestContext(request)
    context_dict = {}    
    
    poll = get_object_or_404(Poll, pk=poll_id)
    context_dict['poll'] = poll
    return render_to_response('polls/results.html', context_dict, context)

def vote(request, poll_id):
    # Get the context from the request, init an empty dict to be passed
    context = RequestContext(request)
    context_dict = {}
    
    p = get_object_or_404(Poll, pk=poll_id)
    context_dict['poll'] = p
    
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context_dict['error_message'] = "You didn't select a choice."
        # Redisplay the poll voting form.
        return render_to_response('polls/details.html', context_dict, context)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


        

grappelli/tinymce/examples/templates/layout1.htm
<table border="1">
	<thead>
		<tr>
			<td>Column 1</td>
			<td>Column 2</td>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>Username: {$username}</td>
			<td>Staffid: {$staffid}</td>
		</tr>
	</tbody>
</table>

grappelli/tinymce/examples/templates/snippet1.htm
This is just some <strong>code</strong>.

templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Welcome to Polls!</title>
    </head>

    <body>
        <h1>Welcome to the Polls Application</h1>
        <h2>Vote on your Favorite Superhero Battles</h2>
        <p>Click the Link Below To Get Started</p>
        <a href="/polls/">Enter</a>
    </body>
</html>

templates/polls/details.html
<!DOCTYPE html>
<html>
    <head>
        <title>Poll | {{ poll.question }}</title>
    </head>
    
    <body>
        <h1>{{ poll.question }}</h1>
        
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        
        <form action="{% url 'polls:vote' poll.id %}" method="post">
            {% csrf_token %}
        
            {% for choice in poll.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            <br>
            <input type="submit" value="Vote">
        </form>
    </body>
</html>

templates/polls/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Polls | Index</title>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />        
    </head>
    
    <body>
        <div id="page-container">
            <header>
                <h1>Polls</h1>
                <hr>
            </header>
            
            {% if latest_polls_list %}
                <h2>5 Most Recent Polls</h2>
                <ul>
                    {% for poll in latest_polls_list %}
                        <li><a href="{% url 'polls:details' poll.id %}">{{ poll.question }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <h2>No Polls Available</h2>
            {% endif %}
        </div>    
    </body>
</html>

templates/polls/results.html
<!DOCTYPE html>
<html>
    <head>
        <title>Polls | Results</title>
    </head>
    
    <body>
        <h1>{{ poll.question }}</h1>
        
        <ul>
            {% for choice in poll.choice_set.all %}
                <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
            {% endfor %}
        </ul>
        
        <a href="{% url 'polls:details' poll.id %}">Vote again?</a>          
    </body>
</html>